# Newton (c)
#
# This work is licensed under the MIT License. To view a copy of this
# license, visit
#
#      https://opensource.org/licenses/MIT
#
# Author: Blair Butterworth
#

FROM mysql:8.0

LABEL version="1.0"
LABEL description="A MySQL database instance for use by the Newton web app."
LABEL maintainer="blair.butterworth.17@ucl.ac.uk"


ENV MYSQL_ROOT_PASSWORD "Newton*123"
COPY ./config/newton.cnf /etc/mysql/conf.d/newton.cnf

EXPOSE 3306
