---
- hosts: master_servers
  vars:
    mysql_root_password: Newton*123

  tasks:
    - name: Register MySQL repository
      yum:
        name: https://dev.mysql.com/get/mysql80-community-release-el7-1.noarch.rpm
        state: present

    - name: Install MySQL
      yum:
        name: "{{ item }}"
        state: present
      with_items:
        - mysql-server
        - MySQL-python

    - name: Start MySQL
      service:
        name: mysqld
        state: started
        enabled: yes

    - name: Update database properties
      shell: |
        initial_password=`awk '/A temporary password is generated for/ {a=$0} END{ print a }' /var/log/mysqld.log | awk '{print $(NF)}'`
        mysql -uroot -p"${initial_password}" --connect-expired-password -e "ALTER USER 'root'@'localhost' IDENTIFIED BY 'Newton*123'; flush privileges; "
        echo 'database.populate=true
            database.user=root
            database.password=Newton*123' > /root/code/newton/database.properties




#    - name: Run project
#      shell: ./gradlew appStartDaemon
#      args:
#        chdir: /root/code/newton
