version: "3.6"

services:
  # Configuration for the Newton web app database
  database:
    build: ./database
    image: newton-database
    ports:
      - "3306:3306"
    networks:
      - backend

  # Configuration for the Jupyter service.
  jupyter:
    build: ./jupyter
    image: newton-jupyter
    ports:
      - "8000:8000"
      - "8888:8888"
    volumes:
      - ~/.newton/experiment:/var/newton/experiment
    networks:
      - backend

  # Configuration for the Newton web app
  master:
    build: ./master
    image: newton-master
    ports:
      - "8080:8080"
    depends_on:
      - database
      - jupyter
    networks:
      - backend

networks:
  backend:
