# Newton (c)
#
# This work is licensed under the MIT License. To view a copy of this
# license, visit
#
#      https://opensource.org/licenses/MIT
#
# Author: Blair Butterworth
#

version: "3.6"

services:
  # Configuration for the Lets Encrypt certificate authentication server
  # certbot:
  #   image: newton-certbot
  #   build:
  #     context: ./certbot
  #   ports:
  #     - "80:80"
  #     - "443:443"

  # Configuration for the Newton web app database
  database:
    image: newton-database
    build:
      context: ./database
    ports:
      - "3306:3306"
    networks:
      - backend

  # Configuration for the Jupyter service.
  jupyter:
    image: newton-jupyter
    build: ./jupyter
    ports:
      - "8000:8000"
      - "8888:8888"
    volumes:
      - experiment_repository:/var/newton/experiment
    networks:
      - backend

  # Configuration for the Newton web app
  master:
    image: newton-master
    build:
      context: ./master
      args:
        - database_host=database
        - database_port=3306
        - database_user=root
        - database_password=Newton*123
        - jupyter_host=localhost
        - jupyter_port=8000
        - slave_host=slave
        - slave_port=8080
        - master_host=master
        - master_port=9090
    ports:
      - "9090:9090"
    depends_on:
      - database
      - jupyter
    networks:
      - backend
    volumes:
      - experiment_repository:/root/.newton/experiment

  # Configuration for the Slave service.
  slave:
    image: newton-slave
    build:
      context: ./slave
      args:
        - master_host=master
        - master_port=9090
    ports:
      - "8080:8080"
    networks:
      - backend

networks:
  backend:

volumes:
  experiment_repository:
  # certificate_repository:
