# Newton (c)
#
# This work is licensed under the MIT License. To view a copy of this
# license, visit
#
#      https://opensource.org/licenses/MIT
#
# Author: Blair Butterworth
#

version: "3.6"

services:
  # Configuration for the Newton web app database
  database:
    image: newton-database
    build:
      context: ./database
    ports:
      - "3306:3306"
    networks:
      - backend

  # Configuration for the Jupyter service.
  jupyter:
    image: newton-jupyter
    build: ./jupyter
    ports:
      - "8000:8000"
      - "8888:8888"
    volumes:
      - ~/.newton/experiment:/var/newton/experiment
    networks:
      - backend

  # Configuration for the Newton web app
  master:
    image: newton-master
    build:
      context: ./master
    ports:
      - "8080:8080"
    depends_on:
      - database
      - jupyter
    networks:
      - backend

networks:
  backend:
