apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: database-newton
spec:
  template:
    metadata:
      labels:
        app: database-newton
    spec:
      containers:
      - name: database-newton
        image: newtonregistry.azurecr.io/blairisme/newton-database:latest
        env:
          - name: database_user
          - value: root
          - name: database_password
          - value: Newton*123
        ports:
        - containerPort: 3306
      imagePullSecrets:
      - name: acr-auth
---
apiVersion: v1
kind: Service
metadata:
  name: database-newton
spec:
  type: LoadBalancer
  ports:
  - port: 3306
  selector:
    app: database-newton
