apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: database-newton
spec:
  template:
    metadata:
      labels:
        app: database-newton
    spec:
      containers:
      - name: database-newton
        image: newtonregistry.azurecr.io/blairisme/newton-database:latest
        ports:
        - containerPort: 3306
      imagePullSecrets:
      - name: acr-auth
---
apiVersion: v1
kind: Service
metadata:
  name: database-newton
spec:
  type: LoadBalancer
  ports:
  - port: 3306
  selector:
    app: database-newton
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: master-newton
spec:
  template:
    metadata:
      labels:
        app: master-newton
    spec:
      volumes:
      - name: shared-data
        emptyDir: {}
      securityContext:
        fsGroup: 0
        runAsUser: 0
      containers:
      - name: master-newton
        envFrom:
        - configMapRef:
            name: my-env-var
        image: newtonregistry.azurecr.io/blairisme/newton:latest
        ports:
        - containerPort: 9090
        volumeMounts:
        - name: shared-data
          mountPath: /root/.newton/experiment
        securityContext:
          runAsUser: 0
      - name: jupyter-newton
        envFrom:
        - configMapRef:
            name: my-env-var
        image: newtonregistry.azurecr.io/blairisme/newton-jupyter:latest
        ports:
        - containerPort: 8000
        - containerPort: 8888
        volumeMounts:
        - name: shared-data
          mountPath: /home/newton/experiment
        securityContext:
          runAsUser: 0
      imagePullSecrets:
      - name: acr-auth
---
apiVersion: v1
kind: Service
metadata:
  name: master-newton
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 9090
    targetPort: 9090
  - name: jupyter
    port: 8000
    targetPort: 8000
  - name: jupyter2
    port: 8888
    targetPort: 8888
  selector:
    app: master-newton
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: slave-newton
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: slave-newton
    spec:
      containers:
      - name: slave-newton
        envFrom:
        - configMapRef:
            name: my-env-var
        image: newtonregistry.azurecr.io/blairisme/newton-slave:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: acr-auth
---
apiVersion: v1
kind: Service
metadata:
  name: slave-newton
spec:
  type: LoadBalancer
  ports:
  - port: 8080
  selector:
    app: slave-newton
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-env-var
data:
  slave_host: 'slave-newton'
  slave_port: '8080'
  database_host: 'database-newton'
  database_port: '3306'
  database_user: 'root'
  database_password: 'Newton*123'
  jupyter_host: '65.52.76.99'
  jupyter_port: '8000'
  master_host: 'master-newton'
  master_port: '9090'