apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: database-newton
spec:
  template:
    metadata:
      labels:
        app: database-newton
    spec:
      containers:
      - name: database-newton
        image: newtonregistry.azurecr.io/blairisme/newton-database:latest
        ports:
        - containerPort: 3306
      imagePullSecrets:
      - name: acr-auth
---
apiVersion: v1
kind: Service
metadata:
  name: database-newton
spec:
  type: LoadBalancer
  ports:
  - port: 3306
  selector:
    app: database-newton
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: master-newton
spec:
  template:
    metadata:
      labels:
        app: master-newton
    spec:
      volumes:
      - name: shared-data
        emptyDir: {}
      securityContext:
        fsGroup: 0
        runAsUser: 0
      containers:
      - name: master-newton
        envFrom:
        - configMapRef:
            name: my-env-var
        image: newtonregistry.azurecr.io/blairisme/newton:latest
        ports:
        - containerPort: 9090
        volumeMounts:
        - name: shared-data
          mountPath: /root/.newton/experiment
        securityContext:
          runAsUser: 0
      - name: jupyter-newton
        envFrom:
        - configMapRef:
            name: my-env-var
        image: newtonregistry.azurecr.io/blairisme/newton-jupyter:latest
        ports:
        - containerPort: 8000
        - containerPort: 8888
        volumeMounts:
        - name: shared-data
          mountPath: /home/newton/experiment
        securityContext:
          runAsUser: 0
      imagePullSecrets:
      - name: acr-auth
---
apiVersion: v1
kind: Service
metadata:
  name: master-newton
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 9090
    targetPort: 9090
  - name: jupyter
    port: 8000
    targetPort: 8000
  - name: jupyter2
    port: 8888
    targetPort: 8888
  selector:
    app: master-newton
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: slave-newton
spec:
  template:
    metadata:
      labels:
        app: slave-newton
    spec:
      containers:
      - name: slave-newton
        envFrom:
        - configMapRef:
            name: my-env-var
        image: newtonregistry.azurecr.io/blairisme/newton-slave:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: acr-auth
---
apiVersion: v1
kind: Service
metadata:
  name: slave-newton
spec:
  type: LoadBalancer
  ports:
  - port: 8080
  selector:
    app: slave-newton
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: php-apache
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: slave-newton
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 5
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-env-var
data:
  slave_host: 'slave-newton'
  slave_port: '8080'
  application_host: 'slave-newton'
  application_port: '8080'
  database_host: 'database-newton'
  database_port: '3306'
  database_user: 'root'
  database_password: 'Newton*123'
  jupyter_host: '65.52.76.99'
  jupyter_port: '8000'
  master_host: 'master-newton'
  master_port: '9090'
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: metrics-server:system:auth-delegator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
- kind: ServiceAccount
  name: metrics-server
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: metrics-server-auth-reader
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: extension-apiserver-authentication-reader
subjects:
- kind: ServiceAccount
  name: metrics-server
  namespace: kube-system
---
apiVersion: apiregistration.k8s.io/v1beta1
kind: APIService
metadata:
  name: v1beta1.metrics.k8s.io
spec:
  service:
    name: metrics-server
    namespace: kube-system
  group: metrics.k8s.io
  version: v1beta1
  insecureSkipTLSVerify: true
  groupPriorityMinimum: 100
  versionPriority: 100
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: metrics-server
  namespace: kube-system
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: metrics-server
  namespace: kube-system
  labels:
    k8s-app: metrics-server
spec:
  selector:
    matchLabels:
      k8s-app: metrics-server
  template:
    metadata:
      name: metrics-server
      labels:
        k8s-app: metrics-server
    spec:
      serviceAccountName: metrics-server
      volumes:
      # mount in tmp so we can safely use from-scratch images and/or read-only containers
      - name: tmp-dir
        emptyDir: {}
      containers:
      - name: metrics-server
        image: gcr.io/google_containers/metrics-server-amd64:v0.2.1
        imagePullPolicy: Always
        volumeMounts:
        - name: tmp-dir
          mountPath: /tmp
---
apiVersion: v1
kind: Service
metadata:
  name: metrics-server
  namespace: kube-system
  labels:
    kubernetes.io/name: "Metrics-server"
spec:
  selector:
    k8s-app: metrics-server
  ports:
  - port: 443
    protocol: TCP
    targetPort: 443
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: system:metrics-server
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - nodes
  - nodes/stats
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - "extensions"
  resources:
  - deployments
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: system:metrics-server
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:metrics-server
subjects:
- kind: ServiceAccount
  name: metrics-server
  namespace: kube-system