apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: master-newton
spec:
  template:
    metadata:
      labels:
        app: master-newton
    spec:
      containers:
      - name: master-newton
        image: newtonregistry.azurecr.io/blairisme/newton
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: acr-auth
---
apiVersion: v1
kind: Service
metadata:
  name: master-newton
spec:
  type: LoadBalancer
  ports:
  - port: 8080
  selector:
    app: master-newton