apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: database-newton
spec:
  template:
    metadata:
      labels:
        app: database-newton
    spec:
      containers:
      - name: database-newton
        image: newtonregistry.azurecr.io/blairisme/newton-database:latest
        ports:
        - containerPort: 3306
      imagePullSecrets:
      - name: acr-auth
---
apiVersion: v1
kind: Service
metadata:
  name: database-newton
spec:
  type: LoadBalancer
  ports:
  - port: 3306
  selector:
    app: database-newton
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: master-newton
spec:
  template:
    metadata:
      labels:
        app: master-newton
    spec:
      volumes:
      - name: shared-data
        emptyDir: {}
      containers:
      - name: master-newton
        env:
          - name: slave_host
            value: slave-newton
          - name: slave_port
            value: '8080'
          - name: database_host
            value: database
          - name: database_port
            value: '3306'
          - name: database_user
            value: root
          - name: database_password
            value: Newton*123
          - name: jupyter_host
            value: jupyter
          - name: jupyter_port
            value: '8000'
          - name: master_host
            value: master-newton
          - name: master_port
            value: '9090'
        image: newtonregistry.azurecr.io/blairisme/newton:latest
        ports:
        - containerPort: 9090
        volumeMounts:
        - name: shared-data
          mountPath: ~/.newton/experiment
      - name: jupyter-newton
        image: newtonregistry.azurecr.io/blairisme/newton-jupyter:latest
        ports:
        - containerPort: 8000
        - containerPort: 8888
        volumeMounts:
        - name: shared-data
          mountPath: /var/newton/experiment
      imagePullSecrets:
      - name: acr-auth
---
apiVersion: v1
kind: Service
metadata:
  name: master-newton
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 9090
    targetPort: 9090
  - name: jupyter
    port: 8000
    targetPort: 8000
  - name: jupyter2
    port: 8888
    targetPort: 8888
  selector:
    app: master-newton
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: slave-newton
spec:
  template:
    metadata:
      labels:
        app: slave-newton
    spec:
      containers:
      - name: slave-newton
        env:
          - name: master_host
            value: master-newton
          - name: master_port
            value: '9090'
        image: newtonregistry.azurecr.io/blairisme/newton-slave:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: acr-auth
---
apiVersion: v1
kind: Service
metadata:
  name: slave-newton
spec:
  type: LoadBalancer
  ports:
  - port: 8080
  selector:
    app: slave-newton