apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: master
spec:
  template:
    metadata:
      labels:
        app: master
    spec:
      containers:
      - name: master
        image: newtonregistry.azurecr.io/blairisme/newton:latest
        args: [“database_host=database”, ”database_port=3306”, “database_user=root”, “database_password=Newton*123”, “jupyter_host=jupyter”, “jupyter_port=8000”, “slave_host=slave”, “slave_port=8070”]
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: acr-auth
---
apiVersion: v1
kind: Service
metadata:
  name: master
spec:
  type: LoadBalancer
  ports:
  - port: 8080
  selector:
    app: master