# Newton (c)
#
# This work is licensed under the MIT License. To view a copy of this
# license, visit
#
#      https://opensource.org/licenses/MIT
#
# Author: Blair Butterworth
#

FROM jetty:9.4

LABEL version="1.0"
LABEL description="Contains the Newton web application"
LABEL maintainer="blair.butterworth.17@ucl.ac.uk"



ARG jupyter_host
ENV newton_jupyter_host $jupyter_host


COPY ./libs/master.war /var/lib/jetty/webapps/ROOT.war
EXPOSE 9090


RUN mkdir -p /var/lib/jetty/.newton/experiment

USER root
COPY ./config/wait-for-it.sh /tmp/jetty/wait-for-it.sh
RUN chmod +x /tmp/jetty/wait-for-it.sh
#USER jetty

WORKDIR $JETTY_BASE
CMD /tmp/jetty/wait-for-it.sh database:3306 -t 60 -- java -jar $JETTY_HOME/start.jar -Djetty.port=9090
