# Newton (c)
#
# This work is licensed under the MIT License. To view a copy of this
# license, visit
#
#      https://opensource.org/licenses/MIT
#
# Author: Blair Butterworth
#

FROM jetty:9.4

LABEL version="1.0"
LABEL description="Contains the Newton web application"
LABEL maintainer="blair.butterworth.17@ucl.ac.uk"
MAINTAINER blair.butterworth.17@ucl.ac.uk

ARG database_host
ARG database_port
ARG database_user
ARG database_password
ARG jupyter_host
ARG jupyter_port
ARG slave_host
ARG slave_port
ARG master_host
ARG master_port
ARG user_dir

ENV newton_profile production
ENV newton_database_host $database_host
ENV newton_database_port $database_port
ENV newton_database_user $database_user
ENV newton_database_password $database_password
ENV newton_jupyter_host $jupyter_host
ENV newton_jupyter_port $jupyter_port
ENV newton_slave_host $slave_host
ENV newton_slave_port $slave_port
ENV newton_master_host $master_host
ENV newton_master_port $master_port
ENV user_home user_dir
ENV newton_profile development

COPY ./libs/master.war /var/lib/jetty/webapps/ROOT.war
EXPOSE 9090
EXPOSE 8443

RUN mkdir -p /var/lib/jetty/.newton/experiment

USER root
COPY ./config/wait-for-it.sh /tmp/jetty/wait-for-it.sh
RUN chmod +x /tmp/jetty/wait-for-it.sh
USER jetty

WORKDIR $JETTY_BASE
RUN java -jar ${JETTY_HOME}/start.jar --add-to-startd=ssl,https
RUN rm -rf /var/lib/jetty/start.d/ssl.ini
COPY ./config/ssl.ini /var/lib/jetty/start.d/ssl.ini
COPY ./config/newton.keystore /var/lib/jetty/etc/newton.keystore
COPY ./config/newton.keystore /var/lib/jetty/start.d/etc/newton.keystore

USER root
CMD /tmp/jetty/wait-for-it.sh database:3306 -t 60 -- java -jar $JETTY_HOME/start.jar -Djetty.port=9090
