---
# Newton (c)
#
# This work is licensed under the MIT License. To view a copy of this
# license, visit
#
#      https://opensource.org/licenses/MIT
#
# This script deploys the Newton web server to master servers. The application
# is obtained via GIT, built and then started via a service, defined in the
# newton.service and newton.sh files.  
#
# Author: Blair Butterworth
#
- hosts: master_servers
  vars:
    mysql_root_password: Newton*123
  tasks:
    - name: Stop Newton service
      service:
        name: newton
        state: stopped
      ignore_errors: true

    - include: deploy_mysql.yml

    - name: Download project
      git:
        repo: 'https://github.com/blairisme/newton.git'
        dest: /root/code/newton
        force: yes

    - name: Build project
      shell: ./gradlew clean build
      args:
        chdir: /root/code/newton

    - name: Update database details
      shell: |
        echo 'database.populate=false
            database.user=root
            database.password={{ mysql_root_password }}' > /root/code/newton/database.properties

    - name: Create Newton executable
      template:
        src: "newton.sh"
        dest: "/usr/sbin/"
        owner: root
        mode: 777

    - name: Create Newton service
      template:
        src: "newton.service"
        dest: "/usr/lib/systemd/system/"
        owner: root
        mode: 777

    - name: Update database details
      shell: systemctl daemon-reload

    - name: Start Newton service
      service:
        name: newton
        state: started
