# Newton (c)
#
# This work is licensed under the MIT License. To view a copy of this
# license, visit
#
#      https://opensource.org/licenses/MIT
#
# Author: Blair Butterworth
#

FROM centos:7

LABEL version="1.0"
LABEL description="A Jupyterhub and JupyterLab docker image for use by the Newton web app."
LABEL maintainer="blair.butterworth.17@ucl.ac.uk"
MAINTAINER blair.butterworth.17@ucl.ac.uk

## Install Pip
RUN yum install https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm -y
RUN yum update -y
RUN yum install python36 -y
RUN yum install python36-setuptools -y
RUN easy_install-3.6 pip

## Install Jupyter applications
RUN pip3 install jupyterhub==0.9.1
RUN pip3 install jupyterlab==0.32.1
RUN pip3 install jupyterhub-jwtauthenticator==0.1

# Install libraries required by Jupyter applications
RUN yum install nodejs npm -y
RUN npm install -g configurable-http-proxy

## Setup Jupyter configuration
RUN mkdir /etc/jupyterhub
COPY ./config/jupyterhub_config.py /etc/jupyterhub/jupyterhub_config.py
COPY ./config/newtonspawner.py /etc/jupyterhub/newtonspawner.py
COPY ./config/newtonauthenticator.py /etc/jupyterhub/newtonauthenticator.py
COPY ./config/newton.key /etc/jupyterhub/newton.key

RUN mkdir -p /home/newton/experiment
RUN chmod -R a+rwx /home/newton/experiment

EXPOSE 8000
EXPOSE 8888

WORKDIR /etc/jupyterhub
CMD jupyterhub --ip 0.0.0.0 --port 8000
